name: test
on: [push]
jobs:
  test-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: antaljanosbenjamin/compile-latex@v1.0.0
        with:
          file: test.tex
          args: -pdf
      - run: '(test -f test.pdf && echo PDF exists) || (echo PDF does not exist && exit 1)'
