name: Compile pdf
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compilation
      uses: vinay0410/tectonic-action@master
      with:
        tex_path: 'latex/main.tex'
        push: 'yes'